### ISSUE TITLE
Choose temporal series database

### ISSUE THREAD

**Issue by schweigert** [magrathealabs/jarvis#15]

**Comment by arianerocha** [comment]
Vou listar aqui algumas opções que encontrei para discussão:

- [graphite](https://graphiteapp.org/) - Usado pelo GitHub 
- [timescale](https://www.timescale.com)  - que diz ser mais rápido que influxdb e usa SQL.
- [influx](https://www.influxdata.com/)

**Comment by schweigert** [comment]
timescale é um fork do Postgres com plugins escritos pelo timescale para deixar o banco mais rápido. Não sei se será uma boa escolha, não parece ser muito utilizado por outras empresas.

**Comment by schweigert** [comment]
Influx é bom, porém não utilizei! :cry: :sob:

**Comment by arianerocha** [comment]
Vamos de graphite então?

**Comment by schweigert** [comment]
Vou usar o Graphite. Pelos testes que fiz ele também é mais leve dentro do Docker (250 vs 500mb de ram). Isso vai facilitar o dev e CI @arianerocha .

**Comment by arianerocha** [comment]
**Graphite** - the chosen one
