### ISSUE TITLE
Movimentar câmera com servo motor

### ISSUE THREAD

**Issue by schweigert** [magrathealabs/jarvis#25]
Criar servidor de servo motor que integre com o jarvis

**Comment by schweigert** [comment]
Fonte da ideia: @alfakini

**Comment by guidefreitas** [comment]
Seria legal detalhar um pouco mais qual é o objetivo ou o problema que esta ideia está tentando resolver.

**Comment by schweigert** [comment]
@guidefreitas A camera que é utilizada com o matrix é fixa presa a tela. A ideia seria dar a liberdade de movimento aos que estão trabalhando remoto, para poder focar onde quiserem.
